- name: Install OpenJDK
  apt: name=openjdk-7-jre-headless state=present
  when: java_version | version_compare('1.7.0', '<')

- name: Install Zookeeper
  apt: name=zookeeperd state=present update_cache=yes
